Get participation route
AGES-PUCRS/simulados-back pull request #11
Opened 2018-09-25 01:10 UTC by Edj84

User story "Implementar rota para buscar resultado do simulado"

2018-09-28 18:26 UTC, fabiohsalmeida requested changes

2018-09-28 18:26 UTC, fabiohsalmeida commented on app/controllers/participation.js
> +        ParticipationModel.findOne({
Utilize o await para tratar das promises ao invés do .then, para tornar o código menos complexo de dar manutenção.

Exemplo:

exports.create = **async** function(req,res) {
     ....
     let participation = await ParticipationModel.findOne(...);
}

2018-09-28 18:26 UTC, fabiohsalmeida commented on app/controllers/participation.js
> +            ParticipationModel.update(
Utilize o await neste ponto também.

Exemplo:
let updatedParticipation = await ParticipationModel.update(...);

2018-09-28 18:26 UTC, fabiohsalmeida commented on app/controllers/participation.js
> +                            ParticipationModel.findOne({
Utilize await neste também.

Exemplo:

let participation = await ParticipationModel.findOne(...);

2018-09-28 20:35 UTC, Edj84 commented
Modificações implementadas. 
Não consegui refatorar com let e await a parte final do método, quando a var data é retornada ao usuário.

2018-10-09 19:37 UTC, fabiohsalmeida approved these changes

2018-10-09 19:37 UTC, merged