answer_question
AGES-PUCRS/simulados-back pull request #14
Opened 2018-10-08 21:41 UTC by Edj84

2018-10-08 22:37 UTC, renanpvaz requested changes
Tua branch está com conflito também, faz o pull ou rebase com o dev pra resolver.

2018-10-08 22:37 UTC, renanpvaz commented on app/controllers/answer.js
> +        let choosedAnswer = await AnswerModel.findOne({
A identação está meio estranha, acho que tu não está com o prettier (formatador).

2018-10-08 22:37 UTC, renanpvaz commented on app/controllers/answer.js
> +        errors['participation_id'] = 'Este campo � necess�rio!'
Acho que teu editor não está em utf 8

2018-10-09 20:35 UTC, Edj84 commented
Conflitos solucionados com rebase e formatação ajustada. Obrigado pelo feedback, Renan.

2018-10-15 17:22 UTC, renanpvaz requested changes
Apesar da branch estar atualizada agora, parece que os dois pontos anteriores ainda persistem.

2018-10-15 17:22 UTC, renanpvaz commented on app/controllers/answer.js
> +const choosedAnswer = async (body) => {
Typo aqui, acho que tu quis dizer "chosen".

2018-10-15 17:22 UTC, renanpvaz commented on app/controllers/answer.js
> +        let choosedAnswer = await AnswerModel.findOne({
Sugiro usar um nome diferente da função para evitar shadowing.

2018-10-15 17:22 UTC, renanpvaz commented on app/controllers/answer.js
> +    let correctAnswer = await AlternativeModel.findOne({
Neste caso usar async/await para um único valor daria no mesmo. Pode ser mudado para:
```
const correctAnswer = (body) => AlternativeModel.findOne({...})
```
ou, como preferir
```
const correctAnswer = (body) => {
  return AlternativeModel.findOne({...})
}
```

2018-10-15 17:22 UTC, renanpvaz commented on app/controllers/answer.js
> +        return res.status(404).json({ success: false, error: 'Alternativa nãoencontrada na base de dados!' });
Parece que algumas palavras ficaram sem espaços aqui e em outras mensagens.

2018-10-15 17:22 UTC, renanpvaz commented on app/controllers/answer.js
> +            if (updateStatus[0] === 1) {
Acho que isso poderia ir para uma variável para clareza, algo do tipo 'updateSuccessful', 'didUpdate', 'wasUpdatedSuccessfully', etc.

2018-10-24 22:58 UTC, renanpvaz approved these changes

2018-10-24 23:36 UTC, merged