Parser do parser
AGES-PUCRS/simulados-back pull request #24
Opened 2018-10-24 23:33 UTC by Edj84

Adapting parser to reflect current BD models. 
File "inserts2.sql" contains create tables and inserts commands for entities Practise_Exam, Question, Alternative and PractiseExam_Questions, regarding OAB Exams nºs 20, 21, 22, 24, 25 and 26.
Totalizing 6 exams, 480 questions and 1920 alternatives.

2018-10-25 13:18 UTC, AlanQuadros approved these changes
Apenas aconselho remover os comentários no próximo PR.

2018-10-25 21:48 UTC, homerooliveira requested changes
Aconselho a criar outra branch e copiar o arquivo "inserts2.sql" para essa branch. Desconsiderar todo o código java que foi criado nesta branch(parseDoParser).

2018-10-25 23:04 UTC, Edj84 commented
@homerooliveira, não entendi a lógica de descarte do Java.

2018-10-26 03:42 UTC, Edj84 commented
Criados novos pacotes para evitar sobrescrever os arquivos do parser atual.

2018-10-26 03:43 UTC, merged