Novo simulado
AGES-PUCRS/simulados-back pull request #5
Opened 2018-09-14 00:18 UTC by ricardo93borges

2018-09-14 01:03 UTC, renanpvaz requested changes

2018-09-14 01:03 UTC, renanpvaz commented on app/models/examQuestion.js
> +const sequelize = new Sequelize(config.database, config.username, config.password, {'dialect':config.production.dialect});
É necessário mesmo instanciar uma nova conexão com o banco? Achei que isso só fosse feito uma vez.

2018-09-14 01:03 UTC, renanpvaz commented on app/models/examQuestion.js
> +module.exports = (sequelize, Sequelize) => {
Acho que esta parte ficou bem confusa, especialmente porque está fazendo [shadowing](https://eslint.org/docs/rules/no-shadow) nas variaveis já definidas no topo. Acho que tu precisa fazer um rebase com a dev (`git pull --rebase origin dev`) pois o Fábio havia refatorado isso: 1500b42836d2b652c77041fd987edf8a5bb382df.

2018-09-14 01:03 UTC, renanpvaz commented on app/controllers/exam.js
> +                    let exam = await Exam.create({aob_exam: true, aob_exam_year: date.getFullYear()}).then((exam) => {
Este trecho é redundante pois o `await` já ira resolver com o valor retornado.
```
.then((exam) => {
                        return exam
                    });
```

2018-09-14 01:03 UTC, renanpvaz commented on app/controllers/exam.js
> +        } catch (e) {
Este `catch` nunca vai ser utilizado pois dentro do `try` não está sendo resolvida a promise criada com `Student.findById(body.student_id)`. Sugiro ou utilizar await para o resultado da mesma ou utilizar `.catch(...)` da promise na linha 63.

2018-09-14 01:03 UTC, renanpvaz commented on app/controllers/exam.js
> +exports.create = async function (req, res) {
Acho que este async é desnecessário.

2018-09-14 01:05 UTC, renanpvaz commented
Num outro comentário geral, acho que seria legal definirmos se vamos dar preferência por `const` ou var, arrow functions ou funções declaradas, ou seja, es5 ou es6.

2018-09-15 15:42 UTC, renanpvaz approved these changes

2018-09-15 21:04 UTC, renanpvaz approved these changes

2018-09-17 20:57 UTC, fabiohsalmeida requested changes

2018-09-17 20:57 UTC, fabiohsalmeida commented on app/controllers/auth.js
>  exports.signin = function (req, res) {
Aconselho usar o async/await nesse método, vai tornar mais simples de ler, escrever e dar manutenção. Exemplo:

exports.signin = async function(req, res) {
...
const user = await User.findOne({where: {email: body.email}});
....
}

2018-09-17 20:57 UTC, fabiohsalmeida commented on app/controllers/exam.js
> +        Student.findById(body.student_id).then(async (student) => {
Aconselho criar uma função auxiliar nesse bloco para baixo para tornar mais fácil de dar manutenção.

2018-09-17 20:57 UTC, fabiohsalmeida commented on app/controllers/exam.js
> +                    .then((participation) => {
Aconselho usar o await nessa parte do código também para não ter await junto com then na mesma função.

2018-09-18 12:34 UTC, fabiohsalmeida approved these changes

2018-09-18 23:45 UTC, merged