Answer route implemented
AGES-PUCRS/simulados-back pull request #6
Opened 2018-09-14 02:35 UTC by IsraelDeorce

@POST /answer
req Body:
{
    "question_id": "123",
    "participation_id": "1234",
    "alternative_id": "12345"
}

The autentication was disable for this route for testing purposes. We also need to discuss about the PUT route or if and how we are going to implement the UPDATE option for an answer. For now I decided to let it not accept only one answer with given ids.

Another thing is that the tests require a remote SQL Server to run but we don`t have it yet. While we haven`t solved this problem, i mapped the tests to expect a server error code (500).

2018-09-14 16:09 UTC, IsraelDeorce commented
![](https://github.trello.services/images/mini-trello-icon.png) [Implementar rota para responder uma questão](https://trello.com/c/T51oIyYd/53-implementar-rota-para-responder-uma-quest%C3%A3o)

2018-09-14 16:32 UTC, renanpvaz requested changes

2018-09-14 16:32 UTC, renanpvaz commented on app/controllers/answer.js
> +        let question = await QuestionModel.findOne({ where: { id: body.question_id } }).then((question) => {
O trecho ```.then((question) => { return question })``` não é necessário. Abaixo tem outros lugares onde pode ser removido também.

2018-09-14 16:32 UTC, renanpvaz commented on app/controllers/answer.js
> +        if (!participation) {
Não tenho certeza, mas talvez não seja necessária esta validação. Acredito que um erro deve ser lançado se o registro não existir, vale a pena testar.

2018-09-14 16:32 UTC, renanpvaz commented on app/controllers/answer.js
> +            return res.status(404).json({ success: false, error: 'Alternative not found on database!' });
Considerando que as mensagens de erros _vão_ para o client, talvez deveriam ser em português.

2018-09-14 16:32 UTC, renanpvaz commented on app/controllers/answer.js
> +    if (!body.question_id) {
Acho ok fazer as validações assim, são necessárias de qualquer forma, mas vale a pena considerar usar algum schema validator tipo [jsonschema](https://www.npmjs.com/package/jsonschema).

2018-09-14 16:45 UTC, IsraelDeorce commented on app/controllers/answer.js
> +    if (!body.question_id) {
Vou estudar a sugestão. Fiz desta forma pq foi minha primeira vez. Por enquanto podemos deixar assim?

2018-09-14 16:46 UTC, IsraelDeorce commented on app/controllers/answer.js
> +            return res.status(404).json({ success: false, error: 'Alternative not found on database!' });
Código misturado em português e inglês na API? Não é melhor tratar isso no front?

O que costuma-se fazer?

2018-09-14 16:47 UTC, IsraelDeorce commented on app/controllers/answer.js
> +        if (!participation) {
Também tive dúvida, na dúvida deixei as validações extras.

2018-09-14 16:47 UTC, renanpvaz commented on app/controllers/answer.js
> +            return res.status(404).json({ success: false, error: 'Alternative not found on database!' });
O código pode ficar em inglês mesmo, acho que apenas as mensagens deveriam ser em português, caso contrário não podemos exibi-las no client.

2018-09-14 16:48 UTC, renanpvaz commented on app/controllers/answer.js
> +        if (!participation) {
Se conseguir confirmar acho que seria bom, daria pra remover bastante código que não seria usado.

2018-09-14 16:49 UTC, IsraelDeorce commented on app/controllers/answer.js
> +        let question = await QuestionModel.findOne({ where: { id: body.question_id } }).then((question) => {
Perdi um certo tempo descobrindo como trabalhar com sincronismo em JS. Vou ver se refatoro esta parte para deixar o código mais clean entre a prova q tenh hj no JK e a Ages no LM. Mas em questão de performance e funcionamento está tudo OK né?

2018-09-14 16:50 UTC, renanpvaz commented on app/controllers/answer.js
> +        let question = await QuestionModel.findOne({ where: { id: body.question_id } }).then((question) => {
Não sei ainda, eu normalmente faço primeiro o code review e depois testo a funcionalidade. Porque as alterações podem acabar, por acidente, quebrando a funcionalidade, então vale mais a pena testar depois.

2018-09-14 18:43 UTC, AlanQuadros commented on app/controllers/answer.js
> +            return res.status(404).json({ success: false, error: 'Alternative not found on database!' });
Podemos criar um arquivo específico somente com as mensagens de erro

2018-09-14 21:29 UTC, fabiohsalmeida commented on app.js
> +const answerRoute = require('./app/routes/answer.js')(app);
Não precisa ajustar.

Utilizamos o arquivo de configuração de rota direto no parâmetro de entrada, por tanto, não tem a necessidade de manter em uma constante as rotas que foram criadas, solução proposta:

"require('./app/routes/answer.js)(app);"

2018-09-16 17:29 UTC, IsraelDeorce commented
Pessoal, decidi manter as verificações tendo em vista que meu banco não está fazendo isso por mim. Alterei aonde foi sugerido

2018-09-16 17:30 UTC, renanpvaz approved these changes

2018-09-17 20:41 UTC, fabiohsalmeida approved these changes

2018-09-17 20:41 UTC, fabiohsalmeida commented on app/config/datasource.js
> +db.answers.belongsTo(db.alternatives, {foreignKey: 'alternative_id'});
Pelo que eu havia validado antes todas as foreignKey estavam sendo criadas pelo underscored: true e os campos dos modelos, nesse caso foi necessário marcar a foreignKey?

2018-09-17 21:09 UTC, merged