Questoes do simulado com paginacao
AGES-PUCRS/simulados-back pull request #7
Opened 2018-09-19 02:36 UTC by gregslag

Rota que busca as questões de um simulado implementada contendo os testes unitários.
Foi criado um script sql (config/db/inserts.sql) e json (config/Initial_data/inserts.json) para popular o db de testes.
Esta é a rota inicial, como no momento não esta sendo validado se o usuário está autenticado, não é esperado o id do usuário que vai executar o simulado.

2018-09-19 12:51 UTC, gregslag commented
![](https://github.trello.services/images/mini-trello-icon.png) [Implementar rota para buscar as questões de um simulado, com paginação](https://trello.com/c/RYaZIDnP/61-implementar-rota-para-buscar-as-quest%C3%B5es-de-um-simulado-com-pagina%C3%A7%C3%A3o)

2018-09-19 13:15 UTC, renanpvaz commented
@gregslag sua branch está conflitando. Rode ```git pull --rebase origin dev```, vão aparecer que certos arquivos estão com conflito, então resolva todos os conflitos de cada passo e então rode ```git add .``` e depois ```git rebase --continue```. Itere nesse último passo até que o rebase termine e depois execute ```git push --force-with-lease```.

Uma dica, quando houverem conflitos o terminal vai exibir entre varias mensagens os caminhos dos arquivos com conflitos, algo tipo: 
```
...
CONFLICT: app/routes/user.js
CONFLICT: server.js
...
```

2018-09-19 15:09 UTC, gregslag commented
Fala @renanpvaz !
Executei o rebase e também complementei o arquivo populate.json com os dados que usei para testes.

2018-09-19 17:01 UTC, fabiohsalmeida approved these changes

2018-09-19 17:36 UTC, renanpvaz requested changes

2018-09-19 17:36 UTC, renanpvaz commented on app/controllers/question.js
> +                if (!participation) {
Novamente questiono se o find já não joga um erro caso ele não encontrar o registro, se for o caso não é necessária a verificação.

2018-09-19 17:36 UTC, renanpvaz commented on app/controllers/question.js
> +        } catch (e) {
Nunca irá cair neste catch pois a promise criada com o ```Participation.findOne(...)``` (linha 21) não está sendo resolvida ali. Sugiro remover o try/catch e usar .catch(() => { ... }) na chamada ou usar o await para resolver ela dentro do try, aí sim o erro poderia ser capturado.

2018-09-19 17:36 UTC, renanpvaz commented on app/routes/question.js
> +require('../middleware/passport')(passport);
Acho que essa inicialização só precisa ser feita uma vez. Só fui perceber agora, mas ela está em todas as rotas, talvez deveria ser movida para app.js.

2018-09-19 17:36 UTC, renanpvaz commented on app/routes/question.js
> +    app.get('/questions/:examId?/:lastQuestion?/:amount?', /*passport.authenticate('jwt', {session: false}),*/ questionController.getQuestionsWithPagination)
Não tenho certeza agora, mas o '?' não indica que é opcional? Se for o caso imagino que apenas a quantidade seja opcional pois podemos inferir um valor padrão.

Outra sugestão seria chamar de page e limit invés de lastQuestion e amount. Considerando que este é o padrão que mais vi em rotas com paginação, acredito que ficaria mais claro.

2018-09-19 17:36 UTC, renanpvaz commented on app/controllers/question.js
> +                            db.sequelize.Promise.each(questions, async question =>
Este `Promise` se não me engano é uma referência da API da promise do Bluebird, que não é necessário porque já temos promises nativas. Sugiro usar o .forEach da prototype do array normal: ```questions.forEach(async question => { ... })```.

2018-09-19 17:36 UTC, renanpvaz commented on app/controllers/question.js
> +        "amount": req.query.amount ? req.query.amount : 10
Acho que para evitar varios ternários tu poderia [desestruturar](https://ponyfoo.com/articles/es6#assignment-destructuring) o req.query e usar valores default para as propriedades:
```
const { examId, lastQuestion = 0, amout = 10 } = req.query
```
Assim lastQuestion e amount vão receber aqueles valores se forem undefined.

2018-09-21 00:56 UTC, merged

2018-09-21 04:34 UTC, IsraelDeorce commented
![](https://github.trello.services/images/mini-trello-icon.png) [Implementar tela de visualização de questão durante simulado](https://trello.com/c/qXunxb7I/48-implementar-tela-de-visualiza%C3%A7%C3%A3o-de-quest%C3%A3o-durante-simulado)